apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: prowler-postgres
  namespace: production
  labels:
    app.kubernetes.io/name: prowler-postgres
    app.kubernetes.io/part-of: prowler
    app.kubernetes.io/component: database
spec:
  serviceName: prowler-postgres
  replicas: 1
  updateStrategy:
    type: OnDelete
  selector:
    matchLabels:
      app.kubernetes.io/name: prowler-postgres
  template:
    metadata:
      labels:
        app.kubernetes.io/name: prowler-postgres
        app.kubernetes.io/part-of: prowler
        app.kubernetes.io/component: database
    spec:
      nodeSelector:
        pool: system
      containers:
        - name: postgres
          image: postgres:16.3-alpine3.20
          ports:
            - containerPort: 5432
              name: postgres
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: prowler-secrets
                  key: POSTGRES_ADMIN_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: prowler-secrets
                  key: POSTGRES_ADMIN_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: prowler-secrets
                  key: POSTGRES_DB
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          livenessProbe:
            exec:
              command:
                - sh
                - -c
                - pg_isready -U $(POSTGRES_USER) -d $(POSTGRES_DB)
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 5
          readinessProbe:
            exec:
              command:
                - sh
                - -c
                - pg_isready -U $(POSTGRES_USER) -d $(POSTGRES_DB)
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: postgres-data
      spec:
        storageClassName: linode-block-storage
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
