apiVersion: v1
kind: Service
metadata:
  name: prowler-postgres
  namespace: production
  labels:
    app.kubernetes.io/name: prowler-postgres
    app.kubernetes.io/part-of: prowler
    app.kubernetes.io/component: database
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: 5432
      targetPort: postgres
      protocol: TCP
      name: postgres
  selector:
    app.kubernetes.io/name: prowler-postgres
