apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: prowler-postgres-pdb
  namespace: production
  labels:
    app.kubernetes.io/name: prowler-postgres
    app.kubernetes.io/part-of: prowler
    app.kubernetes.io/component: database
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: prowler-postgres
