apiVersion: apps/v1
kind: Deployment
metadata:
  name: prowler-ui
  namespace: production
  labels:
    app.kubernetes.io/name: prowler-ui
    app.kubernetes.io/part-of: prowler
    app.kubernetes.io/component: ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: prowler-ui
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app.kubernetes.io/name: prowler-ui
        app.kubernetes.io/part-of: prowler
        app.kubernetes.io/component: ui
    spec:
      nodeSelector:
        pool: general
      containers:
        - name: prowler-ui
          image: prowlercloud/prowler-ui:stable
          ports:
            - containerPort: 3000
              name: http
          envFrom:
            - secretRef:
                name: prowler-secrets
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 200m
              memory: 512Mi
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 15
            periodSeconds: 15
            timeoutSeconds: 3
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
