apiVersion: v1
kind: Service
metadata:
  name: prowler-api
  namespace: production
  labels:
    app.kubernetes.io/name: prowler-api
    app.kubernetes.io/part-of: prowler
    app.kubernetes.io/component: api
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
      nodePort: 30080
  selector:
    app.kubernetes.io/name: prowler-api
