---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: rabbitmq-app-credentials
  namespace: production
spec:
  encryptedData:
    RABBITMQ_PASSWORD: AgAD17KpQ7+YlHJOwJmHluMeiqlaJ4HTgRzLSsbjGe4aD7tYICf9Uqm1S57mjX3tBusg5+dF2qADH8ShXVcwH/3n0ntoAXxmVHET6yPYbWP8nnnYUKvQmNp+tHOG03nka58yHBVhn1F1jggheOgh393EP55WYA91DXIpPzgzjctw24fnoxhXiFlMPZ7AWnXlHdkWGq2ckeNuV+TLTC5ybJ06MvxWGLERU4imD88d2NzqeoSHtDO91RvrXlh9R4KRKgudgEvxUMmSDdO7ZyeozIX7vDw9S/0NY/sRnw6uTENmG7wR4VWBvL+f8r1Hl2u4gHez7BekiCeJtTKI6r6MCdjds1aKTtXrNzTjjvXySzq4sXvGw1GJ9parCIzt8nNgw4yaVTIOM75lKdjt3ZW1Pan1/IAX1TYrPNvvEjaMlhqKMc/pqaqfmXuAKaJy9/WtyEj3xrVSrY6UdsC2azRXskafhjfGqQ7hJbujPAWNog2UuyB/uxG3rlOhPeSTwqPI7NqDh0aB+xeaNDAWa1rfooJDoFps2k3Q8vP22WcslEfTlc6PLddEi7nqNgGU9CjyTzCFIoDCvXeHe7uHX+Y9WLAPkbPFLV5fjvvmlBmH8lIzK4S3hSlqLRDITpPdXy748Uts3gWfTXtoJ3+Eemo95B2tDsc5OiDcz+W2Lc9GxpOzjmZTl5GyPU3N0FVlZMy9Tm4vF08qttc0Z86XHMYZm5uRZKFGtwuyyiZl14IhCP+t0ckxm3xiJfxcMWbcaw==
    RABBITMQ_USERNAME: AgAAzpkBi1OlcR0GT2KVQCUXf5fstfXNX2GVzWaVjaUf9fjWPASTLKqCFXaol1IiaGnFm5cmFqh/T+Esf1vZpduiSRXy8KNYs9BH80R/Inq/FntsWqYwA3/KYmAa0TRsjOhEKNAMWaSZemZKU3XMMEMyqVYxkAcAqMtH9Kz8dqzRdwgRmEki0Cav5jsFEFeKr1ktW2vICbA/bBROnXaF74VaI8O2gjh3jCJ+7+yJt8VbWK5J61JpBr8olXaofZQV+9XtzdxDX/Db86yr3IUHtmImlBaExiwcVIgbHBnJsoCm1S89s2ZEn+bSaJ6FGMxOXGoRtJVCKqvpi04fOYVO3tIuahulEFxOuWjlScsK/Z9KMwoplrAYE2ykPqxy1bClvhAQ4xMEZ/HksZzUmrSS5eI8sBJnMyM0OypiE2ljilgyQua3/LL/kB07EXDf2XSLMX25aNYs2ZU2WnxknNrMvgqIcLb17Fei98hANjMki1Kup3gxkOix1r0zHw9Y99psVcKzQgyv8tsmIXXbbogtGUOEuEIDOgBozC1Xv1Gy6Thtz8/Coz0HngSRE4ua1IeGq5H/rdrfQe45yY2spKnYjadlAfIC6SPFGS+PmUn6guSpSOhg9H0n7BvOMA96t+tfp88f/dCcWsWmUk0AlMfzLmYKsFFTqBQwuKUKG7gkJvd3SOYFnf2/JmB28eRl9FSDMdpW0ytuPnRKEhnsTc6a9OljMV54
  template:
    metadata:
      creationTimestamp: null
      name: rabbitmq-app-credentials
      namespace: production
    type: Opaque
