---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: rabbitmq-credentials
  namespace: production
spec:
  encryptedData:
    rabbitmq-erlang-cookie: AgCX/VIbx+MOF4ZT11fjae+t50Ec9xYGq0mZIV9dZvdmdPPYaZFyz2ekodmKwRkqHp66aaRJqMGkEHVAvFqpcm9aiOzhvlvyj3o7Zk4dvD4cdYrjB83cWgiIFO/+g2V86dk/qVBFHVQvhRUz56DrcrzuCEAUMWcOLQp+3WcP66dB/Rk0BXA6/2BE0OpvAzNjra5pEdtEuT58skg6tujtSeTJdg2ywxxmz0h2kC4MMdiLTQxcb0Laat+RQVPkmzKhSmQ1GwgOefb3alBUD0n2KwplkfI8XWIG9PuUSyOzaoV00vyiTegyvXaJ+Hum2SP99Zhs3Bqzdzlapk1SMK3wpRiIq0A3tsdJ9EHRZjIEPT+HvvAYSogaNUtpPqTohs/tE33/4tPCcfKNAEJEcXcudO0x5lQbAHtWUWxroTPgAv3CT0rZZmhuNAWC0HwLl98Q9PwrPL13xnxlhTm8dAU4MKpq+EjNv0LITrjRb1JevP4udKRGgTwVwzxkgO8JWNiUM/LSxqNotYNEWokdzs/QFrqKwMgLHlYskFlv2dtd801fK6t5+8MZv4kHC/4qVckYL7G86f5+ZRAgLzNj03XA6aEfnNwqDcVnXfNYFuUW/kZoEBasQjV0xZws1A3JQGMtZ84FsgDzfEGora/HuuVJMbPvZpdBfvVOXvaqQLeNbm+1Fu0sRDjoR+hKxc5yHpCPoEWDWDa2PGCWjc1NqKeR6rJkJg7H13GTDvIXknHXqj9ofAPtGSPOF0+BgfHnMA==
    rabbitmq-password: AgBRvEaPptiDkYtQxzObD0clIpD8OIQADCh/dkSioGm8EVrIvWTlNZmjLfE9cGru0LkeMMXCo3gcPNTsqcSN8ZVCtBjnlYi3JKpgdnRCxb4W3ySdCu/imBdoSOyuyz4mQiw9qVBLn1b08rIjI481Jx7j2osDZtBV1HV5kXsy1RTGY4n6TPcPwrGyaKQByzoYqBQgoFbKN9MF1Asf3qPWLs4+1G8Yo8b7H594yjXLfOCpo3OLwQEwMul1YmCsQFEiLtR0DZBErBfMNywWJSMZWqTNAa0gEU/u/c+/wNCi5GYbQ/yUl6tBcPZxIYAJEkpVr6tvvR54BpF0zKD1X84pt3I5dzJxuRz+/tqWhi6G3kMmlLlQLBfLQThB191jUNcls8gWXvOFW7IzXpobex5L33AvXApOH9ylNljmK3mrpdUohJLShGJ2R5qNK0Zp/LgdfUv61FGmB5mbKppy7V+LQq2E8+GUVfmbmo/lHWy0i+5zTrZNEfBXJTYpM3BvTytlchJbKxvOwPWLFyzDg28eKQ2cHR02DG2AUTuvmLtonEb0RC2gyzJfhlq1YkWLqx6qb/iSjsCxPQNbkGaqZRgGohTSrY+AMQvrMEdAHQU6UuLW6owQTeK3Rxi9iixpMWZZtzrY8CqqwQEAunQKhun4sBjfhGpSNZ9QQ4zpAV4pPKBi3oS42WUSXN5ARA976oIUftrtlf1t3Dx29xYp3oziI1HRcjAAq5oHmmYF7zMax8sbTZ/dq9M+ZJespFS2uw==
  template:
    metadata:
      creationTimestamp: null
      name: rabbitmq-credentials
      namespace: production
    type: Opaque
