apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tts-microservice
  namespace: argocd
  labels:
    team: backend
    tier: customer-facing
spec:
  project: creatium

  source:
    repoURL: https://github.com/creatium/infra.git
    targetRevision: main
    path: kubernetes/charts/creatium-service
    helm:
      valueFiles:
        - ../../../kubernetes/base/tts-microservice/values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: production

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground

    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
