# =============================================================================
# PersistentVolumeClaim — CSI-provisioned Linode Block Storage volume
# =============================================================================
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: judwaa-nfs-storage
  namespace: production
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: linode-block-storage-retain
  resources:
    requests:
      storage: 500Gi
