---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: azure-model-transfer
  namespace: production
spec:
  encryptedData:
    AZURE_ACCOUNT_KEY: AgBkJVLWY+ASiLRb8mycmx6Ueq0+RPr6NE/c8FFKHI4GuYvCwlrbKDtYdaoBJOsGEHYJpjaZT4sRB9tAtGkMWQscTxOx+kDFgaCOukx5xayzPoTk2imPAe3Z6RG3EykuB4N9xzVmaW9xfk55cKvf/bUA6NT8RpmYkhh3RTwQ2SSHQAmkbHE/xbCVU2lv7MTMj59dWKX+RnibtOb/KauBpkJQbyBDuTZOZP1cQuTyGmKOf3XP/xG4cxMnZdyVQGzvuU23Vbc/wvt+zIvDjqh1O6uJM21vVHRvK57sAlOMPjVmokbW5TkSv7VJwN5a9OAZl3PSlnYXD1Lt2wUv5CiipA1Ds1gPQ2Bqxu77ywqKX6OgA2MSM3NrgJf6g5qKXEM8JPuCcoSa56WI7Eh0oVm11iDGwyzhmg7VZ1VGw8ry1MCB7luj0DZ5L4IQtskJCbREZ5wQ8BerKn40cFNltlpDiE6gr/+KAdZ3JSYspyX2qYdVqD1Hx8w2FtulxRwApPCgdMFAkee3Huzjof+feJEh9ax5Yg8YeTsTICWR/96L/4pxqeHiyHPBBM3Zrvfl9y0QlKM9yrvh+k3m6TmBUBpMLDSX3NNDf4hcZT9mVeJ+gzOkPpoW9eFiHz8FqsSiyzgM1kUksfvROb58xKDIWFeIwTWkCpM9LrCEhVSWcEZqaPmRAf0BMIOk71baV2kNmm9RUwj8uPHZ156RiBN3Ket378z+RXpp2LUyDEexxahyhOMPABHLYDCgFk8AwSMZNt94aUDpcSGgaPrM6/9O8mlI6tTBX2ujZfZxNiNYR69BdSUZpf8PKfC3yGH8
    AZURE_STORAGE_ACCOUNT: AgBExYBuYATdMNJrrAO8SoUxMFsoFerGutXDw9ghp82jRZ/SaJ4Alse4jrDMw58t5bNHVU3SEdAHhvkjqTIQdv3jcuFIouoUa6biCzOGiq3+RXbZuQjHQ0bwI1Qz2rB4dSOHpBflsSRhoSQiODsZn589PHvWBtQxOWCTQ5Qs1LXEDUFIc+wY01xxkRR1ABkUz3TGCRO9iw9yzoLgi803oG+fv+3i6Ml5HE2/8zTTjB1WP/Ge2NYp6ijU2ux8tKFukF3TKnTaU8dzJpbtZwfYbBAKeIBvIN7UKcWCN1Zm426pq7w5h6YPFp1igHN1CvkHRQ1HDfjwJZ7ozHSYnQisYkXDnq7xkFCWpwcyXkS0hfp63pzt3bNw3T04Br1yRjgGlOKQyPYaDI2lF098p/rWJ8CeqIYOoCroEMmMBxVzkQX1x0u7eCxtHMxkU0JiSNtjfMXWPXiKlWEhXIBVB68ypS5jIPF6O4pYEybxdagOWQbhuZ7fNhI7V9ChNRT9SEyMRqx1nGbUBk4xMnVEyevjfVS/ge7jrPwZoOvhxBiR14pS4AqLH48cA1nFiLEXXbBxORvU0tbam49ZauaSm2xo8jOvAbunEdTGCHcfKnugpc3JBQ/6uEyi96lQPgOM876SUKlp15nyafWspwK8BR7rFfbTmDcdtoj6KkyvShjAZZYfCPEFsF6ZyXlPYFf3HMIRxtMpOfi0Qn60zEy8
  template:
    metadata:
      creationTimestamp: null
      name: azure-model-transfer
      namespace: production
